//pediatric kg went from 0.45kg to 50kg

const drugs = weight => {
  return {
    adult: [
      {
        tradeName: 'propofol',
        useTradeName: true,
        genericName: 'diprivan',
        primaryPurpose: 'induction IV bolus',
        label: 'yellow',
        textColor: 'black',
        uses: [
          {
            purpose: 'induction', //required
            method: 'bolus', //required
            low: 1.5, //required
            high: 2.5, //required
            weightUnits: '/kg',
            onset: null,
            duration: null, //required - leave blank if the dosage is simply mg/min (ie ketamine adjunct)
            perKg: true, //required //do you want it multiplied perKg?
            // range: true, //if the range differs from the dose.  This wasnt needed. when perKg was false, it made for the same logic.
            unitsKg: 'mg', //required
            supplied: 10, //required
            infusionUnits: '', //required
            topLevel: true,
            topNotes: null,
            notes: [], //required
            // showRange: true, //This is a possibility to show the range.  If it is the same as the dose, the information may just muddy the water
            // roundTo: 10  //This is the rounding decimal.  Nobody is going to draw up .5 mg of propofol (unless peds) - so it might be more practical to have a rounding capability for clinical use.
          },
          {
            purpose: 'maintenance',
            method: 'infusion', //IV infusion
            low: 75,
            high: 300,
            weightUnits: '/kg',
            onset: null,
            duration: null,
            onset: null,
            duration: null,
            perKg: true,
            unitsKg: 'mcg',
            supplied: 10,
            infusionUnits: '/min',
            topLevel: false,
            topNotes: null,
            notes: [],
          },
          {
            purpose: 'antiemetic',
            method: 'bolus',
            ss: true, //single shot without
            low: 15,
            high: 20,
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: false,
            supplied: 10,
            unitsKg: 'mg',
            infusionUnits: '',
            topLevel: false,
            topNotes: null,
            notes: [],
          },
          {
            purpose: 'antiemetic',
            method: 'infusion',
            low: 15,
            high: 20,
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: true,
            unitsKg: 'mcg',
            supplied: 10,
            infusionUnits: '/min',
            topLevel: false,
            topNotes: null,
            notes: [],
          },
        ],
      },
      {
        tradeName: 'etomidate',
        useTradeName: true,
        genericName: 'amidate',
        primaryPurpose: 'induction IV bolus',
        label: 'yellow',
        textColor: 'black',
        uses: [
          {
            purpose: 'induction',
            method: 'bolus',
            low: 0.2,
            high: 0.6,
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: true,
            unitsKg: 'mg',
            supplied: 2,
            infusionUnits: '',
            topLevel: true,
            topNotes: null,
            notes: [],
          },
        ],
      },
      {
        tradeName: 'ketamine',
        useTradeName: true,
        genericName: 'ketalar',
        primaryPurpose: 'induction IV bolus',
        label: 'yellow',
        textColor: 'black',
        uses: [
          {
            purpose: 'induction',
            method: 'bolus',
            low: 1.0,
            high: 4.5,
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: true,
            perIBW: true,
            unitsKg: 'mg',
            supplied: 50,
            infusionUnits: '',
            topLevel: true,
            topNotes: null,
            notes: [],
          },
          {
            purpose: 'maintenance adjunct',
            method: 'infusion',
            low: 0.1,
            high: 0.5,
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: false,
            unitsKg: 'mg',
            supplied: 50,
            infusionUnits: '/min',
            topLevel: false,
            topNotes: null,
            notes: [
              'when used as an adjunct, ketamine is most often paired with propofol',
            ],
          },
        ],
      },
      {
        tradeName: 'midazolam',
        useTradeName: false,
        genericName: 'versed',
        primaryPurpose: 'sedation IV bolus',
        label: 'orange',
        textColor: 'black',
        uses: [
          {
            purpose: 'anxiolysis or sedation',
            method: 'bolus',
            low: 1,
            high: 2,
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: false,
            unitsKg: 'mg',
            supplied: 1,
            infusionUnits: '',
            topLevel: true,
            topNotes: null,
            notes: [],
          },
          {
            purpose: 'induction',
            method: 'bolus',
            low: 0.3,
            high: 0.35,
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: true,
            unitsKg: 'mg',
            supplied: 2,
            infusionUnits: '',
            topLevel: false,
            topNotes: null,
            notes: [],
          },
        ],
      },
      {
        tradeName: 'morphine',
        useTradeName: true,
        genericName: '',
        primaryPurpose: 'Analgesic IV bolus',
        label: '#439EE0',
        textColor: 'black',
        uses: [
          {
            purpose: 'analgesia',
            method: 'bolus',
            low: 2.5,
            high: 5.0,
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: false,
            unitsKg: 'mg',
            supplied: 5,
            infusionUnits: '',
            topLevel: true,
            topNotes: 'every 3-4 hours',
            notes: ['every 3-4 hours'],
          },
        ],
      },
      {
        tradeName: 'fentanyl',
        useTradeName: true,
        genericName: 'actiq',
        primaryPurpose: 'Analgesic IV bolus',
        label: '#439EE0',
        textColor: 'black',
        uses: [
          {
            purpose: 'analgesia',
            method: 'bolus',
            low: 1,
            high: 4,
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: true,
            unitsKg: 'mcg',
            supplied: 50,
            infusionUnits: '',
            topLevel: true,
            topNotes: null,
            notes: [],
          },
        ],
      },
      {
        tradeName: 'sufentanil',
        useTradeName: true,
        genericName: 'Sufenta',
        primaryPurpose: 'Analgesic IV infusion',
        label: '#439EE0',
        textColor: 'black',
        uses: [
          {
            purpose: 'analgesia',
            method: 'infusion',
            low: 0.15,
            high: 0.5,
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: true,
            perIBW: true,
            unitsKg: 'mcg',
            supplied: 5,
            infusionUnits: '/hr',
            topLevel: true,
            topNotes:
              'MAX 1.0 mcg/kg/hr \n(combined total infusion + bolus doses)',
            notes: [
              'MAX 1.0 mcg/kg/hr (combined total infusion + bolus doses)',
            ],
          },
        ],
      },

      {
        tradeName: 'hydromorphone',
        useTradeName: false,
        genericName: 'dilaudid',
        primaryPurpose: 'Analgesic IV bolus',
        label: '#439EE0',
        textColor: 'black',
        uses: [
          {
            purpose: 'analgesia',
            method: 'bolus',
            low: 0.2,
            high: 1,
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: false,
            unitsKg: 'mg',
            supplied: 2,
            infusionUnits: '',
            topLevel: true,
            topNotes: 'typically diluted to 0.2 mg/mL using 9cc of NS',
            notes: ['typically diluted to 0.2 mg/mL using 9cc of NS'],
          },
          {
            purpose: 'analgesia',
            method: 'PCA',
            low: 0.3,
            high: 2.4,
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: false,
            unitsKg: 'mg',
            supplied: 0,
            infusionUnits: '/hr',
            topLevel: false,
            topNotes: null,
            notes: [],
          },
        ],
      },
      {
        tradeName: 'remifentanil',
        useTradeName: true,
        genericName: 'ultiva',
        primaryPurpose: 'Analgesic IV infusion',
        label: '#439EE0',
        textColor: 'black',
        uses: [
          {
            purpose: 'analgesia',
            method: 'infusion',
            low: 0.125,
            high: 0.25,
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: true,
            unitsKg: 'mcg',
            supplied: '',
            infusionUnits: '/min',
            topLevel: true,
            topNotes: null,
            notes: [
              'Remifentanil should be administered with a standard dose of an hypnotic agent, such as propofol, thiopentone, or isoflurane, for the induction of anaesthesia. Administering Remifentanil after an hypnotic agent will reduce the incidence of muscle rigidity. Remifentanil can be administered at an infusion rate of 0.5 to 1 microgram/kg/min, with or without an initial bolus injection of 1 microgram/kg given over not less than 30 seconds. If endotracheal intubation is to occur more than 8 to 10 minutes after the start of the infusion of Remifentanil, then a bolus injection is not necessary.',
            ],
          },
        ],
      },
      {
        tradeName: 'succinylcholine',
        useTradeName: true,
        genericName: 'anectine',
        primaryPurpose: 'Intubating paralytic bolus',
        label: '#ed3f17',
        textColor: 'white',
        uses: [
          {
            purpose: 'muscle relaxant',
            method: 'bolus',
            low: 0.5,
            high: 1.5,
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: true,
            unitsKg: 'mg',
            supplied: 20,
            infusionUnits: '',
            topLevel: true,
            topNotes: null,
            notes: [],
          },
        ],
      },
      {
        tradeName: 'rocuronium',
        useTradeName: true,
        genericName: 'zemuron',
        primaryPurpose: 'Intubating paralytic bolus',
        label: '#ed3f17',
        textColor: '#FFFFFF',
        uses: [
          {
            purpose: 'muscle relaxant',
            method: 'bolus',
            low: 0.6,
            high: 1.2,
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: true,
            perIBW: true,
            unitsKg: 'mg',
            supplied: 10,
            infusionUnits: '',
            topLevel: true,
            topNotes: null,
            notes: [],
          },
          {
            purpose: 'maintenance',
            method: 'bolus',
            low: 5,
            high: 10,
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: false,
            unitsKg: 'mg',
            supplied: 10,
            infusionUnits: '',
            topLevel: false,
            topNotes: null,
            notes: [
              'based on train-of-four stimulation (TOF). 2 to 3 twitches to TOF should be present',
            ],
          },
          {
            purpose: 'defasciculation',
            method: 'bolus',
            low: 5,
            high: 10,
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: false,
            unitsKg: 'mg',
            supplied: 10,
            infusionUnits: '',
            topLevel: false,
            topNotes: null,
            notes: [],
          },
        ],
      },
      {
        tradeName: 'vecuronium',
        useTradeName: true,
        genericName: 'norcuron',
        primaryPurpose: 'Intubating paralytic bolus',
        label: '#ed3f17',
        textColor: '#FFFFFF',
        uses: [
          {
            purpose: 'muscle relaxant',
            method: 'bolus',
            low: 0.08,
            high: 0.1,
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: true,
            perIBW: true,
            unitsKg: 'mg',
            supplied: 1,
            infusionUnits: '',
            topLevel: true,
            topNotes:
              '10 mg of powder must be reconstituted using 10 ml sterile water or NS',
            notes: [
              '10 mg of powder must be reconstituted using 10 ml sterile water or NS',
            ],
          },
        ],
      },
      {
        tradeName: 'cisatracurium',
        useTradeName: true,
        genericName: 'nimbex',
        primaryPurpose: 'Intubating paralytic bolus',
        label: '#ed3f17',
        textColor: '#FFFFFF',
        uses: [
          {
            purpose: 'muscle relaxant',
            method: 'bolus',
            low: 0.1,
            high: 0.2,
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: true,
            perIBW: true,
            unitsKg: 'mg',
            supplied: 2,
            infusionUnits: '',
            topLevel: true,
            topNotes: null,
            notes: [],
          },
        ],
      },
      {
        tradeName: 'neosynephrine',
        useTradeName: false,
        genericName: 'phenylephrine',
        primaryPurpose: 'bolus to increase BP',
        label: '#d48bc0',
        textColor: 'black',
        uses: [
          {
            purpose: 'increase BP',
            method: 'bolus',
            low: 50,
            high: 100,
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: false,
            unitsKg: 'mcg',
            supplied: 100,
            infusionUnits: '',
            topLevel: true,
            topNotes: 'this is per dose.  Titrate to effect.',
            notes: [
              'this is per dose. Titrate to effect',
              'anticipate a baroreceptor reflex (drop in heart rate)',
            ],
          },
          {
            purpose: 'increase',
            method: 'infusion',
            low: 40,
            high: 200,
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: false,
            unitsKg: 'mcg',
            supplied: 40,
            infusionUnits: '/min',
            topLevel: false,
            topNotes: null,
            notes: [
              'dilute the 1 ml (10 mg) vial in a 250 mL bag of fluid to achieve 40 mcg/mL',
              'the common infusion rate runs between 40 - 60 mcg/kg/min',
            ],
          },
        ],
      },
      {
        tradeName: 'ephedrine',
        useTradeName: true,
        genericName: 'ephedrine',
        primaryPurpose: 'bolus to increase BP',
        label: '#d48bc0',
        textColor: 'black',
        uses: [
          {
            purpose: 'increase BP',
            method: 'bolus',
            low: 2.5,
            high: 10,
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: false,
            unitsKg: 'mg',
            supplied: 5,
            infusionUnits: '',
            topLevel: true,
            topNotes:
              'This is per dose.  Titrate to effect. Draw up the 1 ml 50 mg vial with 9 mL of fluid to achieve a 5 mg/mL solution',
            notes: [
              'This is per dose.  Titrate to effect',
              'draw up the 1 ml 50 mg vial with 9 mL of fluid to achieve a 5 mg/mL solution',
              'anticipate an increase in heart rate with an increase in blood pressure',
            ],
          },
        ],
      },
      {
        tradeName: 'vasostrict',
        useTradeName: false,
        genericName: 'vasopressin',
        primaryPurpose: 'Bolus to treat vasopegia',
        label: '#d48bc0',
        textColor: 'black',
        uses: [
          {
            purpose: 'increase BP',
            method: 'bolus',
            low: 0.5,
            high: 1,
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: false,
            unitsKg: 'units',
            supplied: 1,
            infusionUnits: '',
            topLevel: true,
            topNotes:
              'This is per dose.  Titrate to effect. Draw up the 1 ml 20 unit vial with 19 mL of fluid to achieve a 1 unit/mL solution',
            notes: ['this is per dose. Titrate to effect'],
          },
        ],
      },
      {
        tradeName: 'adrenalin',
        useTradeName: false,
        genericName: 'epinephrine',
        primaryPurpose: 'bolus to increase BP',
        label: '#d48bc0',
        textColor: 'black',
        uses: [
          {
            purpose: 'increase BP',
            method: 'bolus',
            low: 1,
            high: 5,
            weightUnits: '/kg',
            onset: 'immediate',
            duration: '5-15 min',
            perKg: true,
            unitsKg: 'mcg',
            supplied: 1000,
            infusionUnits: '',
            topLevel: true,
            topNotes: null,
            notes: [
              'doses that are too low will produce HYPOTENSION, so monitor and titrate carefully',
              'anticipate concurrent increases in heart rate',
            ],
          },
          {
            purpose: 'increase BP for severe sustained hypotension',
            method: 'infusion',
            low: 0.02,
            high: 0.5,
            weightUnits: '/kg',
            onset: 'immediate',
            duration: '5-15 min',
            perKg: false,
            unitsKg: 'mcg',
            supplied: 1000,
            infusionUnits: 'min',
            topLevel: false,
            topNotes: null,
            notes: ['anticipate concurrent increases in heart rate'],
          },
        ],
      },
      {
        tradeName: 'cardene',
        useTradeName: false,
        genericName: 'nicardipine',
        primaryPurpose: 'IV infusion to reduce BP',
        label: '#FFFFFF',
        textColor: '#e03339',
        uses: [
          {
            purpose: 'BP reduction',
            method: 'infusion',
            low: 5,
            high: 15,
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: true,
            unitsKg: 'mg',
            supplied: 0.1,
            infusionUnits: '/hr',
            topLevel: true,
            topNotes:
              'single-dose 25 mg 10 mL vials diluted with 240 ml of IV fluid. Titrate 2.5 mg/h every 5 min.',
            notes: [
              'single-dose 25 mg 10 mL vials diluted with 240 ml of IV fluid',
              'titrate 2.5 mg/h every 5 min.  Max: 15 mg/h',
            ],
          },
          {
            purpose: 'BP reduction',
            method: 'bolus',
            low: 1,
            high: 2,
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: false,
            unitsKg: 'mg',
            supplied: 0.1,
            infusionUnits: '',
            topLevel: false,
            topNotes: null,
            notes: [
              'single-dose 25 mg 10 mL vials diluted with 240 ml of IV fluid',
            ],
          },
        ],
      },
      {
        tradeName: 'nipride',
        useTradeName: false,
        genericName: 'nitroprusside',
        primaryPurpose: 'IV infusion to reduce BP',
        label: '#FFFFFF',
        textColor: '#e03339',
        uses: [
          {
            purpose: 'IV infusion to reduce BP',
            method: 'infusion',
            low: 0.5,
            high: 2.0,
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: true,
            unitsKg: 'mcg',
            supplied: '',
            infusionUnits: '/min',
            topLevel: true,
            topNotes:
              'total projected intra-op dosage should not exceed 3-3.5 mg/kg',
            notes: [
              'total projected intra-op dosage should not exceed 3-3.5 mg/kg',
            ],
          },
        ],
      },
      {
        tradeName: 'apresoline',
        useTradeName: false,
        genericName: 'hydralazine',
        primaryPurpose: 'Bolus to reduce BP',
        label: '#FFFFFF',
        textColor: '#e03339',
        uses: [
          {
            purpose: 'reduce BP',
            method: 'bolus',
            low: 3,
            high: 20,
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: false,
            unitsKg: 'mg',
            supplied: 20,
            infusionUnits: '',
            topLevel: true,
            topNotes: 'titrate every 20-60 minutes',
            notes: [
              'slow IV push every 20-60 minutes',
              'titrations in 2-3 mg increments',
            ],
          },
        ],
      },
      {
        tradeName: 'brevibloc',
        useTradeName: false,
        genericName: 'Esmolol',
        primaryPurpose: 'Bolus to reduce BP',
        label: '#926349',
        textColor: '#FFFFFF',
        uses: [
          {
            purpose: 'reduce BP',
            method: 'bolus',
            low: 0.5,
            high: 1,
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: true,
            unitsKg: 'mg',
            supplied: 10,
            infusionUnits: '',
            topLevel: true,
            topNotes: 'given over 30 seconds',
            notes: ['given over 30 seconds'],
          },
          {
            purpose: 'reduce BP',
            method: 'infusion',
            low: 0.15,
            high: 0.3,
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: false,
            unitsKg: 'mg',
            supplied: '',
            infusionUnits: '/min',
            topLevel: false,
            topNotes: null,
            notes: [
              'this infusion is preceded by a loading dose of 1mg/kg over 30 seconds',
            ],
          },
        ],
      },
      {
        tradeName: 'trandate',
        useTradeName: false,
        genericName: 'labetalol',
        primaryPurpose: 'Bolus to reduce BP',
        label: '#926349',
        textColor: '#FFFFFF',
        uses: [
          {
            purpose: 'reduce BP',
            method: 'bolus',
            low: 5,
            high: 20,
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: false,
            unitsKg: 'mg',
            supplied: 5,
            infusionUnits: '',
            topLevel: true,
            topNotes: 'titrate every 5-10 minutes',
            notes: [
              'titrate every 5-10 minutes',
              'maximum dose of 300 mg per 24-hour period',
            ],
          },
          {
            purpose: 'reduce BP',
            method: 'infusion',
            low: 0.5,
            high: 2.0,
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: false,
            unitsKg: 'mg',
            supplied: '',
            infusionUnits: '/min',
            topLevel: false,
            topNotes: null,
            notes: [
              'may be titrated up to 10 mg/kg/min',
              'titrate every 5-10 minutes',
              'maximum dose of 300 mg per 24-hour period',
            ],
          },
        ],
      },
      {
        tradeName: 'xylocaine',
        useTradeName: false,
        genericName: 'lidocaine',
        primaryPurpose: 'Intubation sympathectomy',
        label: '#ababab',
        textColor: 'black',
        uses: [
          {
            purpose: 'sympathectomy',
            method: 'bolus',
            low: 1.0,
            high: 1.5,
            weightUnits: '/kg',
            onset: '1-2 min',
            duration: '1-2 hrs',
            perKg: true,
            perIBW: true,
            unitsKg: 'mg',
            supplied: 20,
            infusionUnits: '',
            topLevel: true,
            topNotes:
              'Max with epinephrine: 7 mg/kg. Max without epinephrine: 4.5 mg/kg',
            notes: [],
          },
        ],
      },
      {
        tradeName: 'marcaine',
        useTradeName: false,
        genericName: 'bupivacaine',
        primaryPurpose: '0.75% spinal bolus',
        label: '#ababab',
        textColor: 'black',
        uses: [
          {
            purpose: 'neuraxial anesthesia',
            method: '0.75% bolus',
            low: 8,
            high: 12,
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: false,
            unitsKg: 'mg',
            supplied: 7.5,
            infusionUnits: '',
            topLevel: true,
            topNotes:
              "height based: < 5'2\" : 1.2 ml, 5'2\"-5'6 : 1.4 ml, > 5'6\" : 1.6 ml",
            notes: [],
          },
        ],
      },
      {
        tradeName: 'robinul',
        useTradeName: true,
        genericName: 'glycopyrrolate',
        primaryPurpose: 'paralytic reversal adjunct',
        label: '#70e266',
        textColor: 'black',
        uses: [
          {
            purpose: 'muscarinic antagonism',
            method: 'bolus',
            low: 0.1,
            high: 0.4,
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: false,
            unitsKg: 'mg',
            supplied: 0.2,
            infusionUnits: '',
            topLevel: false,
            topNotes:
              'used to raise HR, dry secretions. Recommended to titrate 0.1 mg every 2-3 minutes',
            notes: [
              'used to raise HR, dry secretions. Recommended to titrate 0.1 mg every 2-3 minutes',
            ],
          },
          {
            purpose: 'paralytic reversal adjunct',
            method: 'bolus',
            low: 0.2,
            high: 1.0,
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: false,
            unitsKg: 'mg',
            supplied: 0.2,
            infusionUnits: '',
            topLevel: true,
            topNotes:
              '0.2 mg should be given with every 1 mg of Neostigmine when reversing paralytic',
            notes: [
              '0.2 mg should be given with every 1 mg of Neostigmine when reversing paralytic',
            ],
          },
        ],
      },
      {
        tradeName: 'atropen',
        useTradeName: false,
        genericName: 'atropine',
        primaryPurpose: 'muscarinic antagonism bolus',
        label: '#70e266',
        textColor: 'black',
        uses: [
          {
            purpose: 'muscarinic antagonism',
            method: 'bolus',
            low: 0.01,
            high: 0.02,
            weightUnits: '/kg',
            onset: '< 1 min',
            duration: '15-30 min',
            perKg: true,
            unitsKg: 'mg',
            supplied: 0.4,
            infusionUnits: '',
            topLevel: true,
            topNotes: 'used primarily to raise HR',
            notes: ['used primarily to raise HR'],
          },
        ],
      },
      {
        tradeName: 'ondansetron',
        useTradeName: false,
        genericName: 'zofran',
        primaryPurpose: 'PONV prophylaxis bolus',
        label: '#FFFFFF',
        textColor: 'black',
        uses: [
          {
            purpose: 'PONV prophylaxis',
            method: 'bolus',
            low: 0.1,
            high: 0.15,
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: true,
            unitsKg: 'mg',
            supplied: 2,
            infusionUnits: '',
            topLevel: true,
            topNotes: null,
            notes: [],
          },
        ],
      },
      {
        tradeName: 'decadron',
        useTradeName: true,
        genericName: 'dexamethasone',
        primaryPurpose: 'PONV prophylaxis bolus',
        label: '#FFFFFF',
        textColor: 'black',
        uses: [
          {
            purpose: 'PONV prophylaxis',
            method: 'bolus',
            low: 4,
            high: 8,
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: false,
            unitsKg: 'mg',
            supplied: 4,
            infusionUnits: '',
            topLevel: true,
            topNotes: null,
            notes: [],
          },
          {
            purpose: 'airway edema',
            method: 'bolus',
            low: 0.15,
            high: 0.25,
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: true,
            unitsKg: 'mg',
            supplied: 4,
            infusionUnits: '',
            topLevel: false,
            topNotes: null,
            notes: ['given ~4 hrs prior to extubation', 'max: 1 mg/kg/day'],
          },
        ],
      },
      {
        tradeName: 'toradol',
        useTradeName: true,
        genericName: 'ketorolac',
        primaryPurpose: 'analgesia IV bolus',
        label: 'white',
        textColor: 'black',
        uses: [
          {
            purpose: 'analgesia',
            method: 'bolus',
            low: 15,
            high: 30,
            unitsKg: 'mg',
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: false,
            supplied: 30,
            infusionUnits: '',
            max: null,
            topLevel: true,
            topNotes: null,
            notes: [],
          },
        ],
      },
      {
        tradeName: 'dexmedetomidine',
        textColor: 'black',
        genericName: 'precedex',
        primaryPurpose: 'Sedation infusion',
        label: '#FFFFFF',
        uses: [
          {
            purpose: 'sedation',
            method: 'infusion',
            low: 0.2,
            high: 1.0,
            unitsKg: 'mcg',
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: true,
            supplied: 100,
            infusionUnits: '/hr',
            max: null,
            topLevel: true,
            topNotes: `Prepared by adding 2 ml of precedex (100 mcg/ml) to 48 ml of 0.9% NaCl, which makes 4 mcg/ml. \nLoading dose of 0.5 - 1.0 mcg/kg (${
              weight * 0.5
            } - ${weight} mcg) is given over 10 min. \nMaintained at 0.2 - 1.0 mcg/kg/hr, titrated to effect`,
            notes: ['preload with 0.2-1 mcg/kg (over 10-20 min)'],
          },
        ],
      },
      {
        tradeName: 'prostigmine',
        useTradeName: false,
        genericName: 'neostigmine',
        primaryPurpose: 'paralytic reversal',
        label: '#FFFFFF',
        textColor: 'black',
        border: {
          borderStyle: 'dashed',
          borderColor: 'red',
          borderRadius: 5,
          borderWidth: 2,
        },
        uses: [
          {
            purpose: 'paralytic reversal',
            method: 'bolus',
            low: 0.04,
            high: 0.08,
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: true,
            unitsKg: 'mg',
            supplied: 0.5,
            infusionUnits: '',
            max: 5,
            topLevel: true,
            topNotes:
              'MAX 5 mg. Give slowly. Should be given with Robinul (0.2 mg of Robinul for every 1 mg of Neostigmine).',
            notes: [
              'MAX 5 mg. Give slowly',
              'should be given with Robinul (0.2 mg of Robinul for every 1 mg of Neostigmine)',
            ],
          },
        ],
      },
      {
        tradeName: 'bridion',
        useTradeName: false,
        genericName: 'sugammadex',
        primaryPurpose: 'paralytic reversal bolus',
        label: '#FFFFFF',
        textColor: 'black',
        uses: [
          {
            purpose: 'NDNMB reversal',
            method: 'bolus',
            low: 2,
            high: 4,
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: true,
            unitsKg: 'mg',
            supplied: 100,
            infusionUnits: '',
            topLevel: true,
            topNotes:
              '2 mg/kg for moderate blockade.  4 mg/kg for deep blockade',
            notes: [
              '2 mg/kg for moderate blockade.  4 mg/kg for deep blockade',
              'only reverses Rocuronium and Vecuronium',
            ],
          },
        ],
      },
      {
        tradeName: '',
        useTradeName: false,
        genericName: 'Ampicillin',
        primaryPurpose: 'IV Antibiotic',
        label: 'black',
        textColor: 'white',
        uses: [
          {
            purpose: 'antibiotic',
            method: 'IV',
            low: 0.5,
            high: 2.0,
            unitsKg: 'g',
            weightUnits: '',
            onset: null,
            duration: null,
            perKg: false,
            supplied: null,
            infusionUnits: '',
            max: null,
            topLevel: true,
            topNotes: 'typically the dose is 2g q 4-6 hours',
            notes: ['typically the dose is 2g q 4-6 hours'],
          },
        ],
      },
      {
        tradeName: 'Ancef',
        useTradeName: true,
        genericName: 'Cefazolin',
        primaryPurpose: 'IV antibiotic',
        label: 'black',
        textColor: 'white',
        uses: [
          {
            purpose: 'antibiotic',
            method: 'bolus',
            low: 2,
            high: null,
            unitsKg: 'g',
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: false,
            supplied: null,
            infusionUnits: '',
            max: null,
            topLevel: true,
            topNotes: '3g for > 120kg. Dose is q 4 hrs',
            notes: ['3g for > 120kg. Dose is q 4 hrs'],
          },
        ],
      },
      {
        tradeName: 'mefoxin',
        useTradeName: false,
        genericName: 'cefoxitin',
        primaryPurpose: 'IV antibiotic',
        label: 'black',
        textColor: 'white',
        uses: [
          {
            purpose: 'antibiotic',
            method: 'bolus',
            low: 1,
            high: 2,
            unitsKg: 'g',
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: false,
            supplied: null,
            infusionUnits: '',
            max: null,
            topLevel: true,
            topNotes: 'q 4-8 hours',
            notes: [],
          },
        ],
      },
      {
        tradeName: 'Rocephin',
        useTradeName: false,
        genericName: 'Ceftriaxone',
        primaryPurpose: 'IV Antibiotic',
        label: 'black',
        textColor: 'white',
        uses: [
          {
            purpose: 'antibiotic',
            method: 'bolus',
            low: 1,
            high: 2,
            unitsKg: 'g',
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: false,
            supplied: null,
            infusionUnits: '',
            max: null,
            topLevel: true,
            topNotes: 'q 24 hrs',
            notes: ['q 24 hrs'],
          },
        ],
      },
      {
        tradeName: 'cleocin',
        useTradeName: false,
        genericName: 'clindamycin',
        primaryPurpose: 'IV antibiotic',
        label: 'black',
        textColor: 'white',
        uses: [
          {
            purpose: 'antibiotic',
            method: 'bolus',
            low: 600,
            high: 900,
            unitsKg: 'mg',
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: false,
            supplied: null,
            infusionUnits: '',
            max: null,
            topLevel: true,
            topNotes: 'q 6-8 hrs',
            notes: ['q 6-8 hrs'],
          },
        ],
      },
      {
        tradeName: 'gentak',
        useTradeName: false,
        genericName: 'gentamicin',
        primaryPurpose: 'IV antibiotic',
        label: 'black',
        textColor: 'white',
        uses: [
          {
            purpose: 'antibiotic',
            method: 'bolus',
            low: 5,
            high: 7,
            unitsKg: 'mg',
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: true,
            supplied: null,
            infusionUnits: '',
            max: null,
            topLevel: true,
            topNotes: 'q day',
            notes: ['q day'],
          },
        ],
      },
      {
        tradeName: 'flagyl',
        useTradeName: false,
        genericName: 'metronidazole',
        primaryPurpose: 'IV antibiotic',
        label: 'black',
        textColor: 'white',
        uses: [
          {
            purpose: 'antibiotic',
            method: 'bolus',
            low: 7.5,
            high: null,
            unitsKg: 'mg',
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: true,
            supplied: null,
            infusionUnits: '',
            max: null,
            topLevel: true,
            topNotes: 'q 6 hrs. MAX 4g/day',
            notes: [],
          },
        ],
      },
      {
        tradeName: 'Unasyn',
        useTradeName: true,
        genericName: 'Ampicillin/Sulbactam',
        primaryPurpose: 'IV Antibiotic',
        label: 'black',
        textColor: 'white',
        uses: [
          {
            purpose: 'antibiotic',
            method: 'bolus',
            low: 1.5,
            high: 3.0,
            unitsKg: 'g',
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: false,
            supplied: null,
            infusionUnits: '',
            max: null,
            topLevel: true,
            topNotes: 'q 6 hours',
            notes: [],
          },
        ],
      },
      {
        tradeName: 'vancocin',
        useTradeName: false,
        genericName: 'vancomycin',
        primaryPurpose: 'IV antibiotic',
        label: 'black',
        textColor: 'white',
        uses: [
          {
            purpose: 'antibiotic',
            method: 'bolus',
            low: 15,
            high: null,
            unitsKg: 'mg',
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: true,
            supplied: null,
            infusionUnits: '',
            max: null,
            topLevel: true,
            topNotes: 'q 12 hrs. Often dosed 1 gram q 12 hrs',
            notes: ['q 12 hrs. Often dosed 1 gram q 12 hrs'],
          },
        ],
      },
      {
        tradeName: 'zosyn',
        useTradeName: true,
        genericName: 'piperacillin / tazobactam',
        primaryPurpose: 'IV antibiotic',
        label: 'black',
        textColor: 'white',
        uses: [
          {
            purpose: 'antibiotic',
            method: 'bolus',
            low: 3,
            high: null,
            unitsKg: 'g',
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: false,
            supplied: null,
            infusionUnits: '',
            max: null,
            topLevel: true,
            topNotes: 'q 4-6 hrs',
            notes: ['q 4-6 hrs'],
          },
        ],
      },
    ],

    pediatric: [
      {
        tradeName: 'propofol',
        useTradeName: true,
        genericName: 'diprivan',
        primaryPurpose: 'induction IV bolus',
        label: 'yellow',
        textColor: 'black',
        uses: [
          {
            purpose: 'induction',
            method: 'bolus',
            low: 2,
            high: 3,
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: true,
            unitsKg: 'mg',
            supplied: 10,
            infusionUnits: '',
            topLevel: true,
            topNotes: null,
            notes: [],
          },
        ],
      },
      {
        tradeName: 'etomidate',
        useTradeName: true,
        genericName: 'amidate',
        primaryPurpose: 'induction IV bolus',
        label: 'yellow',
        textColor: 'black',
        uses: [
          {
            purpose: 'induction',
            method: 'bolus',
            low: 0.2,
            high: 0.3,
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: true,
            unitsKg: 'mg',
            supplied: 2,
            infusionUnits: '',
            topLevel: true,
            topNotes: null,
            notes: [],
          },
          {
            purpose: 'maintenance',
            method: 'infusion',
            low: 5,
            high: 20,
            unitsKg: 'mcg',
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: true,
            supplied: '',
            infusionUnits: '/min',
            max: null,
            topLevel: false,
            topNotes: null,
            notes: [],
          },
        ],
      },
      {
        tradeName: 'ketamine',
        useTradeName: true,
        genericName: 'ketalar',
        primaryPurpose: 'induction IV bolus',
        label: 'yellow',
        textColor: 'black',
        uses: [
          {
            purpose: 'induction',
            method: 'bolus',
            low: 2,
            high: 3,
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: true,
            unitsKg: 'mg',
            supplied: 50,
            infusionUnits: '',
            topLevel: true,
            topNotes: null,
            notes: [],
          },
          {
            purpose: 'induction',
            method: 'IM',
            low: 5,
            high: 8,
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: false,
            unitsKg: 'mg',
            supplied: 50,
            infusionUnits: '',
            topLevel: false,
            topNotes: null,
            notes: [],
          },
        ],
      },
      {
        tradeName: 'midazolam',
        useTradeName: false,
        genericName: 'versed',
        primaryPurpose: 'PO anxiolysis',
        label: 'orange',
        textColor: 'black',
        uses: [
          {
            purpose: 'anxiolysis',
            method: 'PO',
            low: 0.25,
            high: 1,
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: true,
            unitsKg: 'mg',
            supplied: 2,
            infusionUnits: '',
            max: 20,
            topLevel: true,
            topNotes: 'not to exceed 20 mg',
            notes: [],
          },
          {
            purpose: 'anxiolysis',
            method: 'bolus',
            low: 0.05,
            high: 0.1,
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: true,
            unitsKg: 'mg',
            supplied: 2,
            infusionUnits: '',
            topLevel: false,
            topNotes: null,
            notes: [],
          },
        ],
      },
      {
        tradeName: 'fentanyl',
        useTradeName: true,
        genericName: 'actiq',
        primaryPurpose: 'Analgesic IV bolus',
        label: '#439EE0',
        textColor: 'black',
        uses: [
          {
            purpose: 'analgesia',
            method: 'bolus',
            low: 0.5,
            high: 1,
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: true,
            unitsKg: 'mcg',
            supplied: 50,
            infusionUnits: '',
            topLevel: true,
            topNotes: null,
            notes: [],
          },
          {
            purpose: 'analgesia',
            method: 'IN',
            low: 1,
            high: 2,
            unitsKg: 'mcg',
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: true,
            supplied: '',
            infusionUnits: '',
            max: null,
            topLevel: false,
            topNotes: null,
            notes: [],
          },
          {
            purpose: 'analgesia',
            method: 'infusion',
            low: 1,
            high: 5,
            unitsKg: 'mcg',
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: true,
            supplied: null,
            infusionUnits: '/hr',
            max: null,
            topLevel: false,
            topNotes: null,
            notes: [],
          },
        ],
      },
      {
        tradeName: 'morphine',
        useTradeName: false,
        genericName: 'morphine',
        primaryPurpose: 'Analgesic IV bolus',
        label: '#439EE0',
        textColor: 'black',
        uses: [
          {
            purpose: 'analgesia',
            method: 'bolus',
            low: 0.05,
            high: 0.1,
            unitsKg: 'mg',
            weightUnits: '/kg/dose',
            onset: null,
            duration: null,
            perKg: true,
            supplied: 10,
            infusionUnits: '',
            max: null,
            topLevel: true,
            topNotes: null,
            notes: [],
          },
        ],
      },
      {
        tradeName: 'hydromorphone',
        useTradeName: false,
        genericName: 'dilaudid',
        primaryPurpose: 'Analgesic IV bolus',
        label: '#439EE0',
        textColor: 'black',
        uses: [
          {
            purpose: 'analgesia',
            method: 'bolus',
            low: 5,
            high: 10,
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: true,
            unitsKg: 'mcg',
            supplied: 200,
            infusionUnits: '',
            topLevel: true,
            topNotes: 'diluted to 0.2 mg/mL using 9cc of NS',
            notes: ['diluted to 0.2 mg/mL using 9cc of NS'],
          },
        ],
      },
      {
        tradeName: 'anectine',
        useTradeName: false,
        genericName: 'succinylcholine',
        primaryPurpose: 'intubation paralytic bolus',
        label: '#ed3f17',
        textColor: 'white',
        uses: [
          {
            purpose: 'intubation paralysis',
            method: 'bolus',
            low: 1,
            high: 2,
            unitsKg: 'mg',
            weightUnits: '/kg',
            onset: '30 sec',
            duration: null,
            perKg: true,
            supplied: 20,
            infusionUnits: '',
            max: null,
            topLevel: true,
            topNotes: '< 1 year old: 2-3 mg/kg',
            notes: ['< 1 year old: 2-3 mg/kg'],
          },
        ],
      },
      {
        tradeName: 'zemuron',
        useTradeName: false,
        genericName: 'rocuronium',
        primaryPurpose: 'intubation paralytic bolus',
        label: '#ed3f17',
        textColor: 'white',
        uses: [
          {
            purpose: 'intubation paralysis',
            method: 'bolus',
            low: 0.6,
            high: 1.2,
            unitsKg: 'mg',
            weightUnits: '/kg',
            onset: '1-2 min',
            duration: null,
            perKg: true,
            supplied: 10,
            infusionUnits: '',
            max: null,
            topLevel: true,
            topNotes: null,
            notes: [],
          },
        ],
      },
      {
        tradeName: 'norcuron',
        useTradeName: false,
        genericName: 'vecuronium',
        primaryPurpose: 'intubation paralysis',
        label: '#ed3f17',
        textColor: 'white',
        uses: [
          {
            purpose: 'intubation paralysis',
            method: 'bolus',
            low: 0.08,
            high: 0.1,
            unitsKg: 'mg',
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: true,
            // perIBW: true,
            supplied: 1,
            infusionUnits: '',
            max: null,
            topLevel: true,
            topNotes: 'must be reconstituted to 10 mL to achieve 1 mg/mL',
            notes: ['must be reconstituted to 10 mL to achieve 1 mg/mL'],
          },
        ],
      },
      {
        tradeName: 'nimbex',
        useTradeName: false,
        genericName: 'cisatracurium',
        primaryPurpose: 'intubation paralytic bolus',
        label: '#ed3f17',
        textColor: '#FFFFFF',
        uses: [
          {
            purpose: '`intubation paralytic`',
            method: 'bolus',
            low: 0.1,
            high: 0.2,
            unitsKg: 'mg',
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: true,
            supplied: 2,
            infusionUnits: '',
            max: null,
            topLevel: true,
            topNotes: null,
            notes: [],
          },
        ],
      },
      {
        tradeName: '',
        useTradeName: false,
        genericName: 'atropine',
        primaryPurpose: 'bolus to increase HR',
        label: 'green',
        textColor: 'white',
        uses: [
          {
            purpose: 'increase HR',
            method: 'bolus',
            low: 10,
            high: 20,
            unitsKg: 'mcg',
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: true,
            supplied: 400,
            infusionUnits: '',
            max: null,
            topLevel: true,
            topNotes: null,
            notes: [],
          },
          {
            purpose: 'increase HR',
            method: 'IM',
            low: 20,
            high: 30,
            unitsKg: 'mcg',
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: true,
            supplied: 400,
            infusionUnits: '',
            max: null,
            topLevel: false,
            topNotes: null,
            notes: [],
          },
          {
            purpose: 'increase HR',
            method: 'PO',
            low: 20,
            high: 30,
            unitsKg: 'mcg',
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: true,
            supplied: null,
            infusionUnits: '',
            max: null,
            topLevel: false,
            topNotes: null,
            notes: [],
          },
        ],
      },
      {
        tradeName: 'robinul',
        useTradeName: true,
        genericName: 'glycopyrrolate',
        primaryPurpose: 'NMB reversal bolus',
        label: 'green',
        textColor: 'white',
        uses: [
          {
            purpose: 'NMB reversal',
            method: 'bolus',
            low: 0.004,
            high: 0.016,
            unitsKg: 'mg',
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: true,
            supplied: 0.2,
            infusionUnits: '',
            max: 5.0,
            topLevel: true,
            topNotes: '0.2 mg of glycopyrrolate for every 1 mg of neostigmine.',
            notes: [],
          },
        ],
      },
      {
        tradeName: 'prostigmine',
        useTradeName: false,
        genericName: 'neostigmine',
        primaryPurpose: 'paralytic reversal',
        label: '#FFFFFF',
        textColor: 'black',
        border: {
          borderStyle: 'dashed',
          borderColor: 'red',
          borderRadius: 5,
          borderWidth: 2,
        },
        uses: [
          {
            purpose: 'paralytic reversal',
            method: 'bolus',
            low: 0.04,
            high: 0.08,
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: true,
            unitsKg: 'mg',
            supplied: 0.5,
            max: 5.0,
            infusionUnits: '',
            topLevel: true,
            topNotes:
              'MAX 5.0 mg. Give slowly. Should be given with Robinul (0.2 mg of Robinul for every 1 mg of Neostigmine). ',
            notes: [
              'MAX 5.0 mg. Give slowly',
              'should be given with Robinul (0.2 mg of Robinul for every 1 mg of Neostigmine)',
            ],
          },
        ],
      },
      {
        tradeName: 'ofirmev',
        useTradeName: true,
        genericName: 'acetaminophen',
        primaryPurpose: 'analgesia IV bolus',
        label: '#FFFFFF',
        textColor: 'red',
        uses: [
          {
            purpose: 'analgesia',
            method: 'bolus',
            low: 10,
            high: 15,
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: true,
            unitsKg: 'mg',
            supplied: 10,
            infusionUnits: '',
            max: null,
            topLevel: true,
            topNotes: 'For patients > 2 years old.  Max: 75 mg/kg/24hrs',
            notes: ['For patients > 2 years old.', 'Max: 75 mg/kg/24hrs'],
          },
          {
            purpose: 'analgesia',
            method: 'PO',
            low: 10,
            high: 15,
            unitsKg: 'mg or mcg',
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: true,
            supplied: '',
            infusionUnits: '',
            max: null,
            topLevel: false,
            topNotes: null,
            notes: ['Max: 75 mg/kg/24hrs'],
          },
          {
            purpose: 'analgesia',
            method: 'IR',
            low: 40,
            high: 40,
            unitsKg: 'mg',
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: true,
            supplied: null,
            infusionUnits: '',
            max: null,
            topLevel: false,
            topNotes: null,
            notes: ['Max: 75 mg/kg/24hrs'],
          },
        ],
      },
      {
        tradeName: 'ondansetron', //https://www.accessdata.fda.gov/drugsatfda_docs/label/2012/020007s043lbl.pdf
        useTradeName: false,
        genericName: 'zofran',
        primaryPurpose: 'PONV prophylaxis bolus',
        label: '#FFFFFF',
        textColor: 'black',
        uses: [
          {
            purpose: 'PONV prophylaxis',
            method: 'bolus',
            low: 0.15,
            high: null,
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: true,
            unitsKg: 'mg',
            supplied: 2,
            infusionUnits: '',
            max: 16,
            topLevel: true,
            topNotes: 'MAX 16 mg',
            notes: ['MAX 16 mg'],
          },
        ],
      },
      {
        tradeName: 'decadron',
        useTradeName: true,
        genericName: 'dexamethasone',
        primaryPurpose: 'PONV prophylaxis bolus',
        label: 'white',
        textColor: 'black',
        uses: [
          {
            purpose: 'PONV',
            method: 'bolus',
            low: 0.1,
            high: 0.15,
            unitsKg: 'mg',
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: true,
            supplied: 4,
            infusionUnits: '',
            max: null,
            topLevel: true,
            topNotes: null,
            notes: [],
          },
          {
            purpose: 'airway edema',
            method: 'bolus',
            low: 0.25,
            high: 0.5,
            unitsKg: 'mg',
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: true,
            supplied: 4,
            infusionUnits: '',
            max: null,
            topLevel: false,
            topNotes: null,
            notes: [],
          },
          {
            purpose: 'ICP',
            method: 'bolus',
            low: 0.5,
            high: 1.5,
            unitsKg: 'mg',
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: true,
            supplied: 4,
            infusionUnits: '',
            max: null,
            topLevel: true,
            topNotes: null,
            notes: [],
          },
        ],
      },
      {
        tradeName: 'toradol',
        useTradeName: true,
        genericName: 'ketorolac',
        primaryPurpose: 'analgesia IV bolus',
        label: 'white',
        textColor: 'black',
        uses: [
          {
            purpose: 'analgesia',
            method: 'bolus',
            low: 0.5,
            high: 1.0,
            unitsKg: 'mg',
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: true,
            supplied: 30,
            infusionUnits: '',
            max: null,
            topLevel: true,
            topNotes: 'PRN doses after the initial dose are q6h (0.5 mg/kg)',
            notes: [],
          },
        ],
      },
      {
        tradeName: 'dexmedetomidine',
        textColor: 'black',
        genericName: 'precedex',
        primaryPurpose: 'sedation bolus',
        label: '#FFFFFF',
        uses: [
          {
            purpose: 'sedation',
            method: 'bolus',
            low: 0.25,
            high: 0.5,
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: true,
            unitsKg: 'mcg',
            supplied: 100,
            infusionUnits: '',
            topLevel: true,
            topNotes: null,
            notes: [],
          },
          {
            purpose: 'sedation',
            method: 'infusion',
            low: 0.2,
            high: 1.0,
            unitsKg: 'mcg',
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: true,
            supplied: 100,
            infusionUnits: '/hr',
            max: null,
            topLevel: false,
            topNotes: null,
            notes: ['preload with 0.2-1 mcg/kg (over 10-20 min)'],
          },
        ],
      },
      {
        tradeName: '',
        useTradeName: false,
        genericName: 'adenosine',
        primaryPurpose: 'Tachycardia Bolus',
        label: '#FFFFFF',
        textColor: 'black',
        uses: [
          {
            purpose: '',
            method: 'bolus',
            low: 0.1,
            high: 0.2,
            unitsKg: 'mg',
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: true,
            supplied: 3,
            infusionUnits: '',
            max: null,
            topLevel: true,
            topNotes:
              'push and immediately follow with fluid flush. IV bolus may be repeated after 2 minutes',
            notes: [
              'push and immediately follow with fluid flush',
              'IV bolus may be repeated after 2 minutes',
            ],
          },
        ],
      },
      {
        tradeName: 'nexterone',
        useTradeName: false,
        genericName: 'amiodarone',
        primaryPurpose: 'antiarrhythmic infusion',
        label: 'white',
        textColor: 'black',
        uses: [
          {
            purpose: 'antiarrhythmic',
            method: 'infusion',
            low: 5,
            high: 10,
            unitsKg: 'mcg',
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: true,
            supplied: '',
            infusionUnits: '/min',
            max: null,
            topLevel: true,
            topNotes: 'precede with a 5 mg/kg IV load (max 150 mg)',
            notes: [],
          },
        ],
      },
      {
        tradeName: 'solu-cortef',
        useTradeName: false,
        genericName: 'hydrocortisone',
        primaryPurpose: 'stress dose bolus',
        label: 'white',
        textColor: 'black',
        uses: [
          {
            purpose: 'stress dose',
            method: 'bolus',
            low: 1,
            high: 2,
            unitsKg: 'mg',
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: true,
            supplied: 50,
            infusionUnits: '',
            max: null,
            topLevel: true,
            topNotes:
              'if < 1 year old: 25-150 mg/day after initial dose. If > 1 year old: 150-250 mg/day after initial dose',
            notes: [
              'if < 1 year old: 25-150 mg/day after initial dose. If > 1 year old: 150-250 mg/day after initial dose',
            ],
          },
        ],
      },
      {
        tradeName: 'bridion',
        useTradeName: false,
        genericName: 'sugammadex',
        primaryPurpose: 'paralytic reversal bolus',
        label: '#FFFFFF',
        textColor: 'black',
        uses: [
          {
            purpose: 'NDNMB reversal',
            method: 'bolus',
            low: 2,
            high: 4,
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: true,
            unitsKg: 'mg',
            supplied: 100,
            infusionUnits: '',
            topLevel: true,
            topNotes:
              '2 mg/kg for moderate blockade.  4 mg/kg for deep blockade',
            notes: [
              '2 mg/kg for moderate blockade.  4 mg/kg for deep blockade',
              'only reverses Rocuronium and Vecuronium',
            ],
          },
        ],
      },
      // {
      //   tradeName: 'dobutrex',
      //   useTradeName: false,
      //   genericName: 'dobutamine',
      //   primaryPurpose: '',
      //   label: '#d48bc0',
      //   textColor: 'black',
      //   uses: [
      //     {
      //       purpose: '',
      //       method: 'infusion',
      //       low: 0.5,
      //       high: 20,
      //       unitsKg: 'mcg',
      //       weightUnits: '/kg',
      //       onset: null,
      //       duration: null,
      //       perKg: true,
      //       supplied: '',
      //       infusionUnits: '/min',
      //       max: null,
      //       topLevel: true,
      //       topNotes: null,
      //       notes: [],
      //     },
      //   ],
      // },
      {
        tradeName: 'ephedrine',
        useTradeName: false,
        genericName: 'ephedrine',
        primaryPurpose: 'bolus to raise BP & HR',
        label: '#d48bc0',
        textColor: 'black',
        uses: [
          {
            purpose: 'increase HR & BP',
            method: 'bolus',
            low: 0.1,
            high: 0.2,
            unitsKg: 'mg',
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: true,
            supplied: 5,
            infusionUnits: '',
            max: null,
            topLevel: true,
            topNotes:
              'draw up the 1 ml 50 mg vial with 9 mL of fluid to achieve a 5 mg/mL solution',
            notes: [
              'draw up the 1 ml 50 mg vial with 9 mL of fluid to achieve a 5 mg/mL solution',
              'anticipate an increase in heart rate with an increase in blood pressure',
            ],
          },
        ],
      },
      {
        tradeName: 'brevibloc',
        useTradeName: false,
        genericName: 'Esmolol',
        primaryPurpose: 'Bolus to reduce HR',
        label: '#926349',
        textColor: '#FFFFFF',
        uses: [
          {
            purpose: 'reduce HR & BP',
            method: 'bolus',
            low: 0.5,
            high: 1,
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: true,
            unitsKg: 'mg',
            supplied: 10,
            infusionUnits: '',
            topLevel: true,
            topNotes: 'given over 30 seconds',
            notes: ['given over 30 seconds'],
          },
          {
            purpose: 'reduce HR & BP',
            method: 'infusion',
            low: 0.05,
            high: 0.15,
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: false,
            unitsKg: 'mg',
            supplied: '',
            infusionUnits: '/min',
            topLevel: false,
            topNotes: null,
            notes: [
              'this infusion is preceded by a loading dose of 1mg/kg over 30 seconds',
            ],
          },
        ],
      },
      {
        tradeName: 'trandate',
        useTradeName: false,
        genericName: 'labetalol',
        primaryPurpose: 'Bolus to reduce BP',
        label: '#926349',
        textColor: '#FFFFFF',
        uses: [
          {
            purpose: 'reduce BP',
            method: 'bolus',
            low: 0.1,
            high: null,
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: true,
            unitsKg: 'mg',
            supplied: 5,
            infusionUnits: '',
            topLevel: true,
            topNotes: 'titrate every 5-10 minutes',
            notes: [
              'titrate every 5-10 minutes',
              'maximum dose of 300 mg per 24-hour period',
            ],
          },
        ],
      },
      // {
      //   tradeName: '*intralipid',
      //   useTradeName: true,
      //   genericName: 'intralipid',
      //   primaryPurpose: 'LA toxicity bolus',
      //   label: 'white',
      //   textColor: 'black',
      //   uses: [
      //     {
      //       purpose: 'LA toxicity',
      //       method: 'bolus',
      //       low: 1.5,
      //       high: '',
      //       unitsKg: 'mL',
      //       weightUnits: '/kg',
      //       onset: null,
      //       duration: null,
      //       perKg: true,
      //       supplied: null,
      //       infusionUnits: '',
      //       max: null,
      //       topLevel: true,
      //       topNotes: 'initial bolus followed by infusion (0.25 mL/kg/min - 0.5 mL/kg/min)',
      //       notes: [],
      //     },
      //   ],
      // },
      {
        tradeName: 'xylocaine',
        useTradeName: false,
        genericName: 'lidocaine',
        primaryPurpose: 'Intubation sympathectomy',
        label: '#ababab',
        textColor: 'black',
        uses: [
          {
            purpose: 'sympathectomy',
            method: 'bolus',
            low: 1.0,
            high: 1.5,
            weightUnits: '/kg',
            onset: '1-2 min',
            duration: '1-2 hrs',
            perKg: true,
            unitsKg: 'mg',
            supplied: 20,
            infusionUnits: '',
            topLevel: true,
            topNotes:
              'Max with epinephrine: 7 mg/kg. Max without epinephrine: 4.5 mg/kg',
            notes: [],
          },
        ],
      },
      {
        tradeName: '',
        useTradeName: false,
        genericName: 'Ampicillin',
        primaryPurpose: 'IV Antibiotic',
        label: 'black',
        textColor: 'white',
        uses: [
          {
            purpose: 'antibiotic',
            method: 'IV',
            low: 25,
            high: 50,
            unitsKg: 'mg',
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: true,
            supplied: null,
            infusionUnits: '',
            max: null,
            topLevel: true,
            topNotes: 'q 4-6 hours',
            notes: [],
          },
        ],
      },
      {
        tradeName: 'Ancef',
        useTradeName: true,
        genericName: 'Cefazolin',
        primaryPurpose: 'IV antibiotic',
        label: 'black',
        textColor: 'white',
        uses: [
          {
            purpose: 'antibiotic',
            method: 'bolus',
            low: 16.6,
            high: 33.3,
            unitsKg: 'mg',
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: true,
            supplied: null,
            infusionUnits: '',
            max: null,
            topLevel: true,
            topNotes: 'q 4 hrs',
            notes: ['q 4 hrs'],
          },
        ],
      },
      {
        tradeName: 'mefoxin',
        useTradeName: false,
        genericName: 'cefoxitin',
        primaryPurpose: 'IV antibiotic',
        label: 'black',
        textColor: 'white',
        uses: [
          {
            purpose: 'antibiotic',
            method: 'bolus',
            low: 25,
            high: 40,
            unitsKg: 'mg',
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: true,
            supplied: null,
            infusionUnits: '',
            max: null,
            topLevel: true,
            topNotes: 'q 6-8 hrs',
            notes: [],
          },
        ],
      },
      {
        tradeName: 'Rocephin',
        useTradeName: false,
        genericName: 'Ceftriaxone',
        primaryPurpose: 'IV Antibiotic',
        label: 'black',
        textColor: 'white',
        uses: [
          {
            purpose: 'antibiotic',
            method: 'bolus',
            low: 50,
            high: 75,
            unitsKg: 'mg',
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: true,
            supplied: null,
            infusionUnits: '',
            max: null,
            topLevel: true,
            topNotes: 'q 24 hrs',
            notes: ['q 24 hrs'],
          },
        ],
      },
      {
        tradeName: 'cleocin',
        useTradeName: false,
        genericName: 'clindamycin',
        primaryPurpose: 'IV antibiotic',
        label: 'black',
        textColor: 'white',
        uses: [
          {
            purpose: 'antibiotic',
            method: 'bolus',
            low: 6.6,
            high: 13.2,
            unitsKg: 'mg',
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: true,
            supplied: null,
            infusionUnits: '',
            max: null,
            topLevel: true,
            topNotes: 'q 6-8 hrs',
            notes: ['q 6-8 hrs'],
          },
        ],
      },
      {
        tradeName: 'gentak',
        useTradeName: false,
        genericName: 'gentamicin',
        primaryPurpose: 'IV antibiotic',
        label: 'black',
        textColor: 'white',
        uses: [
          {
            purpose: 'antibiotic',
            method: 'bolus',
            low: 1,
            high: 2.5,
            unitsKg: 'mg',
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: true,
            supplied: null,
            infusionUnits: '',
            max: null,
            topLevel: true,
            topNotes: 'q 8 hrs',
            notes: ['q 8 hrs'],
          },
        ],
      },
      {
        tradeName: 'flagyl',
        useTradeName: false,
        genericName: 'metronidazole',
        primaryPurpose: 'IV antibiotic',
        label: 'black',
        textColor: 'white',
        uses: [
          {
            purpose: 'antibiotic',
            method: 'bolus',
            low: 7.5,
            high: null,
            unitsKg: 'mg',
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: true,
            supplied: null,
            infusionUnits: '',
            max: null,
            topLevel: true,
            topNotes: 'q 6 hrs',
            notes: [],
          },
        ],
      },
      {
        tradeName: 'Unasyn',
        useTradeName: true,
        genericName: 'Ampicillin/Sulbactam',
        primaryPurpose: 'IV Antibiotic',
        label: 'black',
        textColor: 'white',
        uses: [
          {
            purpose: 'IV antibiotic',
            method: 'bolus',
            low: 20,
            high: 50,
            unitsKg: 'mg',
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: true,
            supplied: null,
            infusionUnits: '',
            max: null,
            topLevel: true,
            topNotes: 'q 6 hrs',
            notes: [],
          },
        ],
      },
      {
        tradeName: 'vancocin',
        useTradeName: false,
        genericName: 'vancomycin',
        primaryPurpose: 'IV antibiotic',
        label: 'black',
        textColor: 'white',
        uses: [
          {
            purpose: 'antibiotic',
            method: 'bolus',
            low: 13,
            high: null,
            unitsKg: 'mg',
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: true,
            supplied: null,
            infusionUnits: '',
            max: null,
            topLevel: true,
            topNotes: 'q 8 hrs',
            notes: ['q 8 hrs'],
          },
        ],
      },
      {
        tradeName: 'zosyn',
        useTradeName: true,
        genericName: 'piperacillin / tazobactam',
        primaryPurpose: 'IV antibiotic',
        label: 'black',
        textColor: 'white',
        uses: [
          {
            purpose: 'antibiotic',
            method: 'bolus',
            low: 50,
            high: 75,
            unitsKg: 'mg',
            weightUnits: '/kg',
            onset: null,
            duration: null,
            perKg: true,
            supplied: null,
            infusionUnits: '',
            max: null,
            topLevel: true,
            topNotes: 'q 6 hrs',
            notes: ['q 6 hrs'],
          },
        ],
      },
    ],
  };
};

// pediatric: {
//   atropine: {
//     class: 'muscarinic antagonist',
//     iv: {
//       dose: 0.02,
//       unitsKg: 'mg',
//       supplied: 0.4,
//       suppliedUnitsMl: 'mg'
//     }
//   },
//   glycopyrrolate: {
//     class: 'muscarinic antagonist',
//     iv: {
//       dose: 0.004,
//       unitsKg: 'mg',
//       supplied: 0.2,
//       suppliedUnitsMl: 'mg'
//     }
//   },
//   midazolam: {
//     class: 'benzodiazepine',
//     iv: {
//       dose: 0.05,
//       unitsKg: 'mg',
//       supplied: 1.0,
//       suppliedUnitsMl: 'mg'
//     }
//   },
//   succinylcholine: {
//     class: 'paralytic',
//     iv: {
//       dose: 2.0,
//       unitsKg: 'mg',
//       supplied: 20,
//       suppliedUnitsMl: 'mg',
//     },
//   },
//   propofol: {
//     class: 'IV sedative',
//     iv: {
//       dose: 3.0,
//       unitsKg: 'mg',
//       supplied: 10,
//       suppliedUnitsMl: 'mg',
//     },
//   },
//   etomidate: {
//     class: 'IV sedative',
//     iv: {
//       dose: 0.3,
//       unitsKg: 'mg',
//       supplied: 20,
//       suppliedUnitsMl: 'mg',
//     },
//   },
//   fentanyl: {
//     class: 'opioid',
//     iv: {
//       dose: 1,
//       unitsKg: 'mcg',
//       supplied: 50,
//       suppliedUnitsMl: 'mcg',
//     },
//   },
//   morphine: {
//     class: 'opioid',
//     alert: 'if less than 6 months of age, dose should be reduced to 0.05 mg/kg',
//     iv: {
//       dose: 0.1,
//       unitsKg: 'mg',
//       supplied: 10,
//       suppliedUnitsMl: 'mg',
//     },
//   },
//   toradol: {
//     class: 'nsaid',
//     alert: 'should not be given to patients < 2 years of age'
//     iv: {
//       dose: 0.5,
//       unitsKg: 'mg',
//       supplied: 30,
//       suppliedUnitsMl: 'mg',
//     },
//   },
//   acetaminophen: {
//     class: 'analgesic',
//     alert: 'should not be given to patients < 2 years of age',
//     iv: {
//       dose: 15,
//       unitsKg: 'mg',
//       supplied: 10,
//       suppliedUnitsMl: 'mg',
//     },
//   },
//   cisatracurium: {
//     class: 'paralytic',
//     iv: {
//       dose: 0.1,
//       unitsKg: 'mg',
//       supplied: 2,
//       suppliedUnitsMl: 'mg',
//     },
//   },
//   rocuronium: {
//     class: 'paralytic',
//     alert: 'if performing RSI, increase dose to 1.2 mg/kg',
//     iv: {
//       dose: 0.6,
//       unitsKg: 'mg',
//       supplied: 10,
//       suppliedUnitsMl: 'mg',
//     },
//   },
//   vecuronium: {
//     class: 'paralytic',
//     iv: {
//       dose: 0.1,
//       unitsKg: 'mg',
//       supplied: 1,
//       suppliedUnitsMl: 'mg',
//     },
//   },
//   neostigmine: {
//     class: 'reversal',
//     iv: {
//       dose: 0.07,
//       unitsKg: 'mg',
//       supplied: 1,
//       suppliedUnitsMl: 'mg',
//     },
//   },
//   dexamethasone: {
//     class: 'ponv',
//     iv: {
//       dose: 0.25,
//       unitsKg: 'mg',
//       supplied: 10,
//       suppliedUnitsMl: 'mg',
//     },
//   },
//   ondansetron: {
//     class: 'ponv',
//     iv: {
//       dose: 0.15,
//       unitsKg: 'mg',
//       supplied: 2,
//       suppliedUnitsMl: 'mg',
//     },
//   },
// },
// }

export default drugs;
